project_id = "reejpxxcemymyvzoakus"

[functions.analyze-image]
verify_jwt = false

[functions.gemini-enhance]
verify_jwt = false

[functions.kie-enhance]
verify_jwt = false

[functions.realesrgan-enhance]
verify_jwt = false